alias md="mkdir -p"
alias rd="rmdir"
alias history="omz_history"
alias h="history"
alias hs="history | grep -i"
alias rsh="source ~/.zshrc"
alias -="cd -"
alias ll="ls -la"
alias ls="ls -G"
alias cpcfg="cp ~/.zshrc ~/code/config/ && cp ~/.oh-my-zsh/themes/agnoster.zsh-theme ~/code/config/ && cp ~/Library/Application\ Support/Code/User/settings.json ~/code/config/ && cp ~/Library/Application\ Support/Code/User/keybindings.json ~/code/config"

# git
alias ga="git add"
alias gaa="git add --all"
alias gb="git branch"
alias gbd="git branch --delete"
alias gbD="git branche --delete --force"
alias gba="git branch --all"
alias gcb="git branch -b"
alias gcm="git checkout $(git_main_branch)"
alias gco="git commit -m"
alias gpull="git pull"
alias gpush="git push"
alias gsu="git push --set-upstream origin "$(git_current_branch)""
alias gl="glods --all"
alias gs="git status --short --branch"
alias gundo="git reset --mixed HEAD^"
alias gfp="git push --force-with-lease origin HEAD:main"
alias gsh="git show"
alias gwip="git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message "--wip-- [skip ci]""
alias egrep="grep -E"
alias fgrep="grep -F"
alias grep="grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox,.venv,venv}"

# pip
alias pipg="pip freeze | grep"
alias pipi="pip install"
alias pipir="pip install -r requirements.txt"
alias pipl="pip list -o"
alias pipiu="pip install --upgrade"
alias pipu="pip uninstall"

# vim
alias vsh="vim ~/.zshrc"
alias vsht="vim ~/.oh-my-zsh/themes/agnoster.zsh-theme"
